apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vvb7jegcn-python 
  janus-idp.io/tekton: vvb7jegcn-python
  backstage.io/kubernetes-id: vvb7jegcn-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vvb7jegcn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml